#!/usr/bin/env python3
"""
generate_handout.py — Generate a polished LaTeX handout from downloaded MOOC materials.

This script is the final step of the mooc2handout pipeline. It reads:
  - VTT subtitles (for lecture content)
  - Supplementary PDFs (extracted text)
  - Keyframe screenshots (for visual references)
  - keyframes.json (for timestamp metadata)

And produces a publication-quality LaTeX handout with:
  - Beautiful typographic design
  - Video links with ▶ symbol for each lecture
  - Bold key concepts
  - Supplementary material summaries
  - Exercise walkthroughs
  - Keyframe screenshots embedded

Usage:
    python3 generate_handout.py \
        --data-dir /tmp/mooc-demo/mathematical-thinking \
        --course-title "Mathematical Thinking" \
        --unit-title "Module 1: Introduction" \
        --instructor "Keith Devlin" \
        --output handout.tex

    # Then compile:
    xelatex handout.tex && xelatex handout.tex
"""

import argparse
import json
import re
import sys
from pathlib import Path


# ── LaTeX Template ────────────────────────────────────────────────────────────

TEXT = {
    "zh": {
        "docclass": r"\documentclass[UTF8,a4paper,11pt]{ctexart}",
        "toc_name": "",
        "review": "回看：",
        "generated_by": "由 mooc2handout 自动生成",
        "title_instructor": "授课教师：",
        "title_note": "本讲义由课程字幕、补充材料与 AI 推断关键帧自动生成。",
        "overview": "0. 概要",
        "knowledge_map": "本单元知识地图",
        "knowledge_topic": "主题",
        "knowledge_question": "核心问题",
        "lesson_review": "回看：",
        "supplement_summary": "内容摘要",
        "supplement_label": "补充材料",
        "key_takeaways": "本单元最该记住的{count}句话",
        "exercises": "练习题",
        "mcq": "选择题（{count}题）",
        "truefalse": "判断题（{count}题）",
        "shortanswer": "简答题（{count}题）",
        "answers": "参考答案",
        "mcq_answers": "选择题答案",
        "truefalse_answers": "判断题答案",
        "shortanswer_answers": "简答题要点",
        "keyframe_reason": {
            "concept_shift": "概念转折",
            "definition": "核心定义",
            "example": "示例讲解",
            "summary": "总结回顾",
            "interval": "内容节选",
        },
        "keyframe_caption": "时间戳 {time}s — {reason}",
    },
    "en": {
        "docclass": r"\documentclass[a4paper,11pt]{article}",
        "toc_name": "Contents",
        "review": "Review:",
        "generated_by": "Generated by mooc2handout",
        "title_instructor": "Instructor:",
        "title_note": "This handout was generated from lecture captions, supplementary materials, and AI-inferred keyframes.",
        "overview": "0. Overview",
        "knowledge_map": "Knowledge Map",
        "knowledge_topic": "Topic",
        "knowledge_question": "Core Question",
        "lesson_review": "Review:",
        "supplement_summary": "Summary",
        "supplement_label": "Supplementary material",
        "key_takeaways": "Key Takeaways",
        "exercises": "Exercises",
        "mcq": "Multiple Choice ({count} questions)",
        "truefalse": "True/False ({count} questions)",
        "shortanswer": "Short Answer ({count} questions)",
        "answers": "Answer Key",
        "mcq_answers": "Multiple Choice",
        "truefalse_answers": "True/False",
        "shortanswer_answers": "Short Answer Key Points",
        "keyframe_reason": {
            "concept_shift": "Concept shift",
            "definition": "Core definition",
            "example": "Example",
            "summary": "Summary",
            "interval": "Excerpt",
        },
        "keyframe_caption": "Timestamp {time}s - {reason}",
    },
}


def get_text(lang: str, key: str) -> str:
    return TEXT[lang][key]


def contains_cjk(text: str) -> bool:
    return bool(re.search(r"[\u4e00-\u9fff]", text))


def build_preamble(lang: str, course_title: str, unit_title: str, instructor: str, data_dir: Path) -> str:
    preamble = "\n".join(
        [
            TEXT[lang]["docclass"],
            "",
            "% ── Page geometry ──",
            r"\usepackage[margin=2.2cm,top=2.5cm,bottom=2.5cm]{geometry}",
            "",
            "% ── Typography ──",
            r"\usepackage{fontspec}",
            r"\usepackage{setspace}",
            r"\setstretch{1.2}",
            "",
            "% ── Graphics ──",
            r"\usepackage{graphicx}",
            rf"\graphicspath{{{{{(data_dir / 'frames').as_posix()}/}}}}",
            "",
            "% ── Colors ──",
            r"\usepackage{xcolor}",
            r"\definecolor{accent}{HTML}{1a73e8}",
            r"\definecolor{darkgray}{HTML}{333333}",
            r"\definecolor{lightgray}{HTML}{f5f5f5}",
            r"\definecolor{keyframebg}{HTML}{fafafa}",
            r"\definecolor{videoblue}{HTML}{065fd4}",
            r"\definecolor{notebg}{HTML}{e8f0fe}",
            r"\definecolor{warnbg}{HTML}{fef7e0}",
            "",
            "% ── Links ──",
            r"\usepackage{hyperref}",
            rf"\hypersetup{{",
            r"  colorlinks=true,",
            r"  linkcolor=accent,",
            r"  urlcolor=videoblue,",
            r"  citecolor=accent,",
            rf"  pdftitle={{{tex_escape(course_title)}}},",
            rf"  pdfauthor={{{tex_escape(instructor)}}}",
            r"}",
            "",
            "% ── Layout ──",
            r"\usepackage{enumitem}",
            r"\setlist[itemize]{leftmargin=1.8em,itemsep=2pt}",
            r"\setlist[enumerate]{leftmargin=1.8em,itemsep=2pt}",
            r"\usepackage{booktabs}",
            r"\usepackage{longtable}",
            r"\usepackage{tcolorbox}",
            r"\usepackage{titlesec}",
            r"\usepackage{fancyhdr}",
            r"\usepackage{lastpage}",
            r"\usepackage{amssymb}",
            "",
            "% ── Header/Footer ──",
            r"\pagestyle{fancy}",
            r"\fancyhf{}",
            rf"\fancyhead[L]{{\small\textcolor{{darkgray}}{{{tex_escape(course_title)}}}}}",
            rf"\fancyhead[R]{{\small\textcolor{{darkgray}}{{{tex_escape(unit_title)}}}}}",
            r"\fancyfoot[C]{\small\textcolor{darkgray}{\thepage\ / \pageref{LastPage}}}",
            r"\renewcommand{\headrulewidth}{0.4pt}",
            "",
            "% ── Section styling ──",
            r"\titleformat{\section}",
            r"  {\Large\bfseries\color{accent}}",
            r"  {\thesection}{1em}{}",
            r"\titleformat{\subsection}",
            r"  {\large\bfseries\color{darkgray}}",
            r"  {\thesubsection}{1em}{}",
            "",
            "% ── Custom environments ──",
            r"\newtcolorbox{keyconcept}{",
            r"  colback=notebg, colframe=accent,",
            r"  fonttitle=\bfseries, boxrule=0.5pt,",
            r"  left=8pt, right=8pt, top=6pt, bottom=6pt",
            r"}",
            r"\newtcolorbox{supplement}{",
            r"  colback=lightgray, colframe=darkgray,",
            r"  fonttitle=\bfseries, boxrule=0.3pt,",
            r"  left=8pt, right=8pt, top=6pt, bottom=6pt",
            r"}",
            r"\newtcolorbox{exercise}{",
            r"  colback=warnbg, colframe=orange,",
            r"  fonttitle=\bfseries, boxrule=0.5pt,",
            r"  left=8pt, right=8pt, top=6pt, bottom=6pt",
            r"}",
            "",
            "% ── Video link command ──",
            r"\newcommand{\videolink}[2]{%",
            r"  \href{#1}{\textcolor{videoblue}{\textbf{#2}}}%",
            r"}",
            "",
            "% ── Keyframe figure command ──",
            r"\newcommand{\keyframe}[2]{%",
            r"  \begin{center}",
            r"    \fcolorbox{lightgray}{keyframebg}{%",
            r"      \includegraphics[width=0.75\linewidth]{#1}%",
            r"    }",
            r"    \par\vspace{2pt}",
            r"    {\small\textcolor{darkgray}{#2}}",
            r"  \end{center}",
            r"}",
            "",
            r"\begin{document}",
        ]
    )
    if lang == "en":
        preamble = "\n".join([preamble, r"\renewcommand{\contentsname}{Contents}"])
    return preamble + "\n"


def build_title_page(lang: str, course_title: str, unit_title: str, instructor: str, course_title_en: str, unit_title_en: str) -> str:
    lines = [r"\begin{center}", r"  \vspace*{2cm}"]
    if lang == "en":
        lines.extend(
            [
                rf"  {{\Huge\bfseries\color{{accent}} {tex_escape(course_title_en or course_title)}}}\\[0.3cm]",
                rf"  {{\LARGE {tex_escape(unit_title_en or unit_title)}}}\\[1.2cm]",
                rf"  {{\large {get_text(lang, 'title_instructor')} {tex_escape(instructor)}}}\\[0.5cm]",
                rf"  {{\large\textcolor{{darkgray}}{{{get_text(lang, 'generated_by')}}}}}\\[0.3cm]",
                r"  {\small\textcolor{darkgray}{\today}}",
                r"  \vfill",
                rf"  {{\small {get_text(lang, 'title_note')}}}",
            ]
        )
    else:
        lines.extend(
            [
                rf"  {{\Huge\bfseries\color{{accent}} {tex_escape(course_title)}}}\\[0.3cm]",
                rf"  {{\small\textcolor{{darkgray}}{{{tex_escape(course_title_en or course_title)}}}}}\\[0.8cm]",
                rf"  {{\LARGE {tex_escape(unit_title)}}}\\[0.3cm]",
                rf"  {{\small\textcolor{{darkgray}}{{{tex_escape(unit_title_en or unit_title)}}}}}\\[1.2cm]",
                rf"  {{\large {get_text(lang, 'title_instructor')} {tex_escape(instructor)}}}\\[0.5cm]",
                rf"  {{\large\textcolor{{darkgray}}{{{get_text(lang, 'generated_by')}}}}}\\[0.3cm]",
                r"  {\small\textcolor{darkgray}{\today}}",
                r"  \vfill",
                rf"  {{\small {get_text(lang, 'title_note')}}}",
            ]
        )
    lines.extend([r"\end{center}", r"\newpage"])
    return "\n".join(lines) + "\n"


def build_toc(lang: str) -> str:
    return "\n".join([r"\tableofcontents", r"\newpage"]) + "\n"


# ── Content extraction ────────────────────────────────────────────────────────

def extract_vtt_text(vtt_path: Path) -> str:
    """Extract clean text from a VTT file."""
    text = vtt_path.read_text(encoding="utf-8", errors="replace")
    text = re.sub(r"WEBVTT.*?\n\n", "", text, flags=re.DOTALL)
    text = re.sub(r"\d{1,2}:\d{2}:\d{2}\.\d{3}\s*-->\s*\d{1,2}:\d{2}:\d{2}\.\d{3}", "", text)
    text = re.sub(r"<[^>]+>", "", text)
    lines = [l.strip() for l in text.splitlines() if l.strip()]
    return " ".join(lines)


def extract_pdf_text(pdf_path: Path, max_pages: int = 5) -> str:
    """Extract text from a PDF file."""
    try:
        import pdfplumber
        texts = []
        with pdfplumber.open(pdf_path) as pdf:
            for page in pdf.pages[:max_pages]:
                t = page.extract_text()
                if t:
                    texts.append(t)
        return "\n\n".join(texts)
    except Exception as e:
        return f"[PDF extraction failed: {e}]"


def tex_escape(text: str) -> str:
    """Escape special LaTeX characters."""
    return (
        text.replace("\\", r"\textbackslash{}")
        .replace("&", r"\&")
        .replace("%", r"\%")
        .replace("$", r"\$")
        .replace("#", r"\#")
        .replace("_", r"\_")
        .replace("{", r"\{")
        .replace("}", r"\}")
        .replace("~", r"\textasciitilde{}")
        .replace("^", r"\textasciicircum{}")
    )


# ── Handout generation ────────────────────────────────────────────────────────

def generate_handout(
    data_dir: Path,
    course_title: str,
    unit_title: str,
    instructor: str,
    output: Path,
    course_title_en: str = "",
    unit_title_en: str = "",
    lang: str = "zh",
    insert_keyframes: bool = False,
):
    """Generate a complete LaTeX handout."""

    if lang not in TEXT:
        raise SystemExit(f"unsupported language: {lang}")

    display_course_title = course_title if lang == "zh" else (course_title_en or course_title)
    display_unit_title = unit_title if lang == "zh" else (unit_title_en or unit_title)
    if lang == "en" and (contains_cjk(display_course_title) or contains_cjk(display_unit_title)):
        raise SystemExit(
            "English output requires English course and unit titles; pass --course-title-en and --unit-title-en"
        )

    # Load manifest
    manifest_path = data_dir / "manifest.json"
    if not manifest_path.exists():
        print(f"Error: {manifest_path} not found", file=sys.stderr)
        sys.exit(1)

    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    if lang == "en" and any(contains_cjk(item.get("title", "")) for item in manifest):
        raise SystemExit("English output requires English lecture titles in manifest.json; re-download with --locale en")

    # Load keyframes
    keyframes_path = data_dir / "keyframes.json"
    keyframes = []
    if keyframes_path.exists():
        keyframes = json.loads(keyframes_path.read_text(encoding="utf-8"))

    # Build LaTeX
    tex = []

    tex.append(build_preamble(lang, display_course_title, display_unit_title, instructor, data_dir))
    tex.append(build_title_page(lang, course_title, unit_title, instructor, course_title_en, unit_title_en))
    tex.append(build_toc(lang))

    # ── Load content.json (language-aware) ──
    content_json_path = data_dir / ("content_en.json" if lang == "en" else "content.json")
    if not content_json_path.exists():
        if lang == "en":
            raise SystemExit(f"missing required English content file: {content_json_path}")
        content_data = {}
    else:
        content_data = json.loads(content_json_path.read_text(encoding="utf-8"))

    # ── Knowledge Map ──
    knowledge_map = content_data.get("knowledge_map", [])
    if knowledge_map:
        tex.append(rf"\section*{{{get_text(lang, 'knowledge_map')}}}")
        tex.append(r"\begin{longtable}{p{3.1cm}p{10.2cm}}")
        tex.append(r"\toprule")
        tex.append(rf"{get_text(lang, 'knowledge_topic')} & {get_text(lang, 'knowledge_question')} \\")
        tex.append(r"\midrule")
        for row in knowledge_map:
            topic = row.get("topic", "")
            question = row.get("question", "")
            tex.append(f"{topic} & {question} \\\\")
        tex.append(r"\bottomrule")
        tex.append(r"\end{longtable}")
        tex.append("")

    # ── Section 0: Overview ──
    overview = content_data.get("overview", "")
    tex.append(rf"\section*{{{get_text(lang, 'overview')}}}")
    if overview:
        tex.append(overview)
    else:
        tex.append(
            r"This unit covers the core concepts of the course."
            if lang == "en"
            else r"本单元涵盖课程的核心概念。"
        )
    tex.append("")

    # ── Per-lecture sections ──
    lecture_summaries = content_data.get("lectures", {})
    for i, item in enumerate(manifest):
        lecture_title = item["title"]
        section_num = i + 1

        tex.append(f"\\section*{{{section_num}. {tex_escape(lecture_title)}}}")

        # Video link with duration
        video_url = item.get("page_url", "")
        duration = item.get("duration", "")
        dur_str = f"({duration})" if lang == "en" and duration else f"（{duration}）" if duration else ""
        if video_url:
            tex.append(
                rf"\noindent\textbf{{{get_text(lang, 'lesson_review')}}}\videolink{{{video_url}}}{{{tex_escape(lecture_title)}}}{dur_str}"
            )
        tex.append("")

        # Per-lecture content from content.json
        video_stem_key = item.get("video", "").replace(".mp4", "") if item.get("video") else ""
        vtt_stem_key = re.sub(r"\.(en|zh-CN|zh-TW|ja|ko|fr|de|es|pt|ar)$", "", item["en_vtt"].replace(".vtt", ""))
        lecture_content = lecture_summaries.get(video_stem_key) or lecture_summaries.get(vtt_stem_key) or ""
        if lecture_content:
            tex.append(lecture_content)
            tex.append("")

        # Supplementary materials
        if item.get("resources"):
            supplements_path = data_dir / ("supplements_en.json" if lang == "en" else "supplements.json")
            supplements_data = {}
            if supplements_path.exists():
                supplements_data = json.loads(supplements_path.read_text(encoding="utf-8"))
            elif lang == "en":
                raise SystemExit(f"missing required English supplement file: {supplements_path}")
            for res_name in item["resources"]:
                if res_name in supplements_data:
                    info = supplements_data[res_name]
                    tex.append(f"\\textbf{{📎 {info['title']}}}")
                    escaped_name = tex_escape(res_name)
                    tex.append(f"\\hfill{{\\small\\texttt{{{escaped_name}}}}}")
                    tex.append("")
                    tex.append(rf"\begin{{supplement}}{{{get_text(lang, 'supplement_summary')}}}")
                    tex.append(r"\begin{itemize}")
                    for para in info.get("summary", []):
                        tex.append(f"  \\item {para}")
                    tex.append(r"\end{itemize}")
                    tex.append(r"\end{supplement}")
                    tex.append("")
                else:
                    clean_name = res_name.split("_", 1)[-1] if "_" in res_name else res_name
                    sep = ":" if lang == "en" else "："
                    tex.append(f"\\textbf{{{get_text(lang, 'supplement_label')}}}{sep}\\texttt{{{tex_escape(clean_name)}}}")
                    tex.append("")

        # Keyframes (optional)
        if insert_keyframes:
            video_stem = item.get("video", "").replace(".mp4", "") if item.get("video") else ""
            lecture_frames = [kf for kf in keyframes if (video_stem and video_stem in kf.get("video", "")) or (vtt_stem_key and vtt_stem_key in kf.get("vtt", ""))]
            if lecture_frames:
                for kf in lecture_frames[:2]:
                    time_label = f"{int(kf['time']):04d}s" if kf['time'] < 60 else f"{int(kf['time'])//60:02d}m{int(kf['time'])%60:02d}s"
                    frame_file = f"{vtt_stem_key}_{time_label}_{kf['reason']}.png"
                    frame_path = data_dir / "frames" / frame_file
                    if frame_path.exists():
                        reason_label = get_text(lang, "keyframe_reason").get(kf["reason"], kf["reason"])
                        caption = get_text(lang, "keyframe_caption").format(time=int(kf["time"]), reason=reason_label)
                        tex.append(f"\\keyframe{{{frame_file}}}{{{caption}}}")
                tex.append("")

    # ── Key Takeaways ──
    key_takeaways = content_data.get("key_takeaways", [])
    if key_takeaways:
        takeaway_num = len(manifest) + 1
        if lang == "en":
            tex.append(rf"\section*{{{takeaway_num}. {get_text(lang, 'key_takeaways')}}}")
        else:
            n = len(key_takeaways)
            cn_num = {3: "三", 4: "四", 5: "五", 6: "六", 7: "七", 8: "八", 9: "九", 10: "十"}.get(n, str(n))
            tex.append(rf"\section*{{{takeaway_num}. {get_text(lang, 'key_takeaways').format(count=cn_num)}}}")
        tex.append(r"\begin{enumerate}")
        for t in key_takeaways:
            tex.append(f"  \\item {t}")
        tex.append(r"\end{enumerate}")
        tex.append("")

    # ── Exercises ──
    exercises = content_data.get("exercises", {})
    answers = content_data.get("answers", {})
    if exercises:
        ex_num = len(manifest) + (2 if key_takeaways else 1)
        tex.append(rf"\section*{{{ex_num}. {get_text(lang, 'exercises')}}}")

        # A. Multiple choice
        choice = exercises.get("choice", [])
        if choice:
            tex.append(rf"\subsection*{{A. {get_text(lang, 'mcq').format(count=len(choice))}}}")
            tex.append(r"\begin{enumerate}")
            for q in choice:
                tex.append(f"  \\item {q['q']}\\\\")
                options = " \\quad ".join(q.get("options", []))
                tex.append(f"  {options}")
                tex.append("")
            tex.append(r"\end{enumerate}")
            tex.append("")

        # B. True/False
        truefalse = exercises.get("truefalse", [])
        if truefalse:
            tex.append(rf"\subsection*{{B. {get_text(lang, 'truefalse').format(count=len(truefalse))}}}")
            tex.append(r"\begin{enumerate}")
            for q in truefalse:
                tex.append(f"  \\item {q}(\\quad)" if lang == "en" else f"  \\item {q}（\\quad）")
            tex.append(r"\end{enumerate}")
            tex.append("")

        # C. Short answer
        shortanswer = exercises.get("shortanswer", [])
        if shortanswer:
            tex.append(rf"\subsection*{{C. {get_text(lang, 'shortanswer').format(count=len(shortanswer))}}}")
            tex.append(r"\begin{enumerate}")
            for q in shortanswer:
                tex.append(f"  \\item {q}")
            tex.append(r"\end{enumerate}")
            tex.append("")

    # ── Answers ──
    if answers:
        ans_num = len(manifest) + (3 if key_takeaways else 2)
        tex.append(rf"\section*{{{ans_num}. {get_text(lang, 'answers')}}}")

        if answers.get("choice"):
            tex.append(rf"\subsection*{{{get_text(lang, 'mcq_answers')}}}")
            tex.append(answers["choice"])
            tex.append("")

        if answers.get("truefalse"):
            tex.append(rf"\subsection*{{{get_text(lang, 'truefalse_answers')}}}")
            tex.append(answers["truefalse"])
            tex.append("")

        if answers.get("shortanswer"):
            tex.append(rf"\subsection*{{{get_text(lang, 'shortanswer_answers')}}}")
            tex.append(r"\begin{enumerate}")
            for a in answers["shortanswer"]:
                tex.append(f"  \\item {a}")
            tex.append(r"\end{enumerate}")
            tex.append("")

    # End document
    tex.append(r"\end{document}")
    
    # Write output
    output.write_text("\n".join(tex), encoding="utf-8")
    print(f"Generated: {output}")
    print(f"  Lectures: {len(manifest)}")
    print(f"  Keyframes: {len(keyframes)}")
    print(f"  Compile with: xelatex {output.name} && xelatex {output.name}")


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Generate a polished LaTeX handout.")
    parser.add_argument("--data-dir", required=True, help="Directory with VTT/PDF/frames")
    parser.add_argument("--course-title", required=True, help="Course title in the output language")
    parser.add_argument("--unit-title", required=True, help="Unit title in the output language")
    parser.add_argument("--course-title-en", default="", help="English course title used for en mode and as a subtitle in zh mode")
    parser.add_argument("--unit-title-en", default="", help="English unit title used for en mode and as a subtitle in zh mode")
    parser.add_argument("--instructor", default="")
    parser.add_argument("--lang", default="zh", choices=["zh", "en"], help="Output language (en requires content_en.json and English titles)")
    parser.add_argument("--keyframes", action="store_true", default=False, help="Insert keyframe screenshots (default: off)")
    parser.add_argument("--output", required=True, help="Output .tex file")
    args = parser.parse_args()
    
    generate_handout(
        data_dir=Path(args.data_dir),
        course_title=args.course_title,
        unit_title=args.unit_title,
        instructor=args.instructor,
        output=Path(args.output),
        course_title_en=args.course_title_en,
        unit_title_en=args.unit_title_en,
        lang=args.lang,
        insert_keyframes=args.keyframes,
    )


if __name__ == "__main__":
    main()
