#!/usr/bin/env python3
"""
generate_handout.py — Generate a polished LaTeX handout from downloaded MOOC materials.

This script is the final step of the mooc2handout pipeline. It reads:
  - VTT subtitles (for lecture content)
  - Supplementary PDFs (extracted text)
  - Keyframe screenshots (for visual references)
  - keyframes.json (for timestamp metadata)

And produces a publication-quality LaTeX handout with:
  - Beautiful typographic design
  - Video links with ▶ symbol for each lecture
  - Bold key concepts
  - Supplementary material summaries
  - Exercise walkthroughs
  - Keyframe screenshots embedded

Usage:
    python3 generate_handout.py \
        --data-dir /tmp/mooc-demo/mathematical-thinking \
        --course-title "Mathematical Thinking" \
        --unit-title "Module 1: Introduction" \
        --instructor "Keith Devlin" \
        --output handout.tex

    # Then compile:
    xelatex handout.tex && xelatex handout.tex
"""

import argparse
import json
import re
import sys
from pathlib import Path


# ── LaTeX Template ────────────────────────────────────────────────────────────

TEXT = {
    "zh": {
        "docclass": r"\documentclass[UTF8,a4paper,11pt]{ctexart}",
        "toc_name": "",
        "review": "回看：",
        "generated_by": "由 mooc2handout 自动生成",
        "title_instructor": "授课教师：",
        "title_note": "本讲义由课程字幕、补充材料与可选的 AI 推断关键帧自动生成。",
        "overview": "0. 概要",
        "diagram": "理解框图",
        "visual_notes": "关键帧观察点",
        "discussion": "延伸讨论",
        "synthesis": "单元串讲",
        "knowledge_map": "本单元知识地图",
        "knowledge_topic": "主题",
        "knowledge_question": "核心问题",
        "lesson_review": "回看：",
        "supplement_summary": "内容摘要",
        "supplement_label": "补充材料",
        "key_takeaways": "本单元最该记住的{count}句话",
        "exercises": "练习题",
        "mcq": "选择题（{count}题）",
        "truefalse": "判断题（{count}题）",
        "shortanswer": "简答题（{count}题）",
        "answers": "参考答案",
        "mcq_answers": "选择题答案",
        "truefalse_answers": "判断题答案",
        "shortanswer_answers": "简答题要点",
        "keyframe_reason": {
            "architecture": "框图 / 架构",
            "concept_shift": "概念转折",
            "definition": "核心定义",
            "comparison": "对比",
            "example": "示例讲解",
            "workflow": "流程 / 步骤",
            "summary": "总结回顾",
            "interval": "内容节选",
        },
        "keyframe_caption": "时间戳 {time}s — {reason}",
    },
    "en": {
        "docclass": r"\documentclass[a4paper,11pt]{article}",
        "toc_name": "Contents",
        "review": "Review:",
        "generated_by": "Generated by mooc2handout",
        "title_instructor": "Instructor:",
        "title_note": "This handout was generated from lecture captions, supplementary materials, and optional AI-inferred keyframes.",
        "overview": "0. Overview",
        "diagram": "Concept Diagram",
        "visual_notes": "Visual Cues",
        "discussion": "Discussion & Extension",
        "synthesis": "Unit Synthesis",
        "knowledge_map": "Knowledge Map",
        "knowledge_topic": "Topic",
        "knowledge_question": "Core Question",
        "lesson_review": "Review:",
        "supplement_summary": "Summary",
        "supplement_label": "Supplementary material",
        "key_takeaways": "Key Takeaways",
        "exercises": "Exercises",
        "mcq": "Multiple Choice ({count} questions)",
        "truefalse": "True/False ({count} questions)",
        "shortanswer": "Short Answer ({count} questions)",
        "answers": "Answer Key",
        "mcq_answers": "Multiple Choice",
        "truefalse_answers": "True/False",
        "shortanswer_answers": "Short Answer Key Points",
        "keyframe_reason": {
            "architecture": "Architecture",
            "concept_shift": "Concept shift",
            "definition": "Core definition",
            "comparison": "Comparison",
            "example": "Example",
            "workflow": "Workflow",
            "summary": "Summary",
            "interval": "Excerpt",
        },
        "keyframe_caption": "Timestamp {time}s - {reason}",
    },
}


def get_text(lang: str, key: str) -> str:
    return TEXT[lang][key]


def contains_cjk(text: str) -> bool:
    return bool(re.search(r"[\u4e00-\u9fff]", text))


def is_likely_english_text(text: str) -> bool:
    """Heuristic filter for extracted text that should stay in English mode."""
    alpha_total = sum(1 for ch in text if ch.isalpha())
    if not alpha_total:
        return False
    ascii_alpha = sum(1 for ch in text if ch.isascii() and ch.isalpha())
    if contains_cjk(text):
        return False
    return ascii_alpha >= 20 and ascii_alpha / alpha_total >= 0.85


def display_resource_name(res_name: str, res_path: Path | None, lang: str) -> str:
    """Return a readable resource label, hiding non-English names in English mode."""
    candidate = ""
    if res_path and res_path.stem:
        candidate = res_path.stem
    elif res_name:
        candidate = Path(res_name).stem
    candidate = candidate.replace("_", " ").strip()
    candidate = re.sub(r"^\d+\s*", "", candidate)
    candidate = re.sub(r"\s+", " ", candidate).strip()
    if not candidate:
        return ""
    if lang == "en" and (contains_cjk(candidate) or not re.search(r"[A-Za-z]", candidate)):
        return ""
    return candidate


def build_preamble(lang: str, course_title: str, unit_title: str, instructor: str, data_dir: Path) -> str:
    preamble = "\n".join(
        [
            TEXT[lang]["docclass"],
            "",
            "% ── Page geometry ──",
            r"\usepackage[margin=2.2cm,top=2.5cm,bottom=2.5cm]{geometry}",
            "",
            "% ── Typography ──",
            r"\usepackage{fontspec}",
            r"\usepackage{setspace}",
            r"\setstretch{1.2}",
            "",
            "% ── Graphics ──",
            r"\usepackage{graphicx}",
            rf"\graphicspath{{{{{(data_dir / 'frames').as_posix()}/}}}}",
            "",
            "% ── Colors ──",
            r"\usepackage{xcolor}",
            r"\definecolor{accent}{HTML}{1a73e8}",
            r"\definecolor{darkgray}{HTML}{333333}",
            r"\definecolor{lightgray}{HTML}{f5f5f5}",
            r"\definecolor{keyframebg}{HTML}{fafafa}",
            r"\definecolor{videoblue}{HTML}{065fd4}",
            r"\definecolor{notebg}{HTML}{e8f0fe}",
            r"\definecolor{warnbg}{HTML}{fef7e0}",
            "",
            "% ── Links ──",
            r"\usepackage{hyperref}",
            rf"\hypersetup{{",
            r"  colorlinks=true,",
            r"  linkcolor=accent,",
            r"  urlcolor=videoblue,",
            r"  citecolor=accent,",
            rf"  pdftitle={{{tex_escape(course_title)}}},",
            rf"  pdfauthor={{{tex_escape(instructor)}}}",
            r"}",
            "",
            "% ── Layout ──",
            r"\usepackage{enumitem}",
            r"\setlist[itemize]{leftmargin=1.8em,itemsep=2pt}",
            r"\setlist[enumerate]{leftmargin=1.8em,itemsep=2pt}",
            r"\usepackage{booktabs}",
            r"\usepackage{longtable}",
            r"\usepackage{tcolorbox}",
            r"\usepackage{titlesec}",
            r"\usepackage{fancyhdr}",
            r"\usepackage{lastpage}",
            r"\usepackage{amssymb}",
            "",
            "% ── Header/Footer ──",
            r"\pagestyle{fancy}",
            r"\fancyhf{}",
            rf"\fancyhead[L]{{\small\textcolor{{darkgray}}{{{tex_escape(course_title)}}}}}",
            rf"\fancyhead[R]{{\small\textcolor{{darkgray}}{{{tex_escape(unit_title)}}}}}",
            r"\fancyfoot[C]{\small\textcolor{darkgray}{\thepage\ / \pageref{LastPage}}}",
            r"\renewcommand{\headrulewidth}{0.4pt}",
            "",
            "% ── Section styling ──",
            r"\titleformat{\section}",
            r"  {\Large\bfseries\color{accent}}",
            r"  {\thesection}{1em}{}",
            r"\titleformat{\subsection}",
            r"  {\large\bfseries\color{darkgray}}",
            r"  {\thesubsection}{1em}{}",
            "",
            "% ── Custom environments ──",
            r"\newtcolorbox{keyconcept}{",
            r"  colback=notebg, colframe=accent,",
            r"  fonttitle=\bfseries, boxrule=0.5pt,",
            r"  left=8pt, right=8pt, top=6pt, bottom=6pt",
            r"}",
            r"\newtcolorbox{supplement}{",
            r"  colback=lightgray, colframe=darkgray,",
            r"  fonttitle=\bfseries, boxrule=0.3pt,",
            r"  left=8pt, right=8pt, top=6pt, bottom=6pt",
            r"}",
            r"\newtcolorbox{exercise}{",
            r"  colback=warnbg, colframe=orange,",
            r"  fonttitle=\bfseries, boxrule=0.5pt,",
            r"  left=8pt, right=8pt, top=6pt, bottom=6pt",
            r"}",
            "",
            "% ── Video link command ──",
            r"\newcommand{\videolink}[2]{%",
            r"  \href{#1}{\textcolor{videoblue}{\textbf{#2}}}%",
            r"}",
            "",
            "% ── Keyframe figure command ──",
            r"\newcommand{\keyframe}[2]{%",
            r"  \begin{center}",
            r"    \fcolorbox{lightgray}{keyframebg}{%",
            r"      \includegraphics[width=0.75\linewidth]{#1}%",
            r"    }",
            r"    \par\vspace{2pt}",
            r"    {\small\textcolor{darkgray}{#2}}",
            r"  \end{center}",
            r"}",
            "",
            r"\begin{document}",
        ]
    )
    if lang == "en":
        preamble = "\n".join([preamble, r"\renewcommand{\contentsname}{Contents}"])
    return preamble + "\n"


def build_title_page(lang: str, course_title: str, unit_title: str, instructor: str, course_title_en: str, unit_title_en: str) -> str:
    lines = [r"\begin{center}", r"  \vspace*{2cm}"]
    if lang == "en":
        lines.extend(
            [
                rf"  {{\Huge\bfseries\color{{accent}} {tex_escape(course_title_en or course_title)}}}\\[0.3cm]",
                rf"  {{\LARGE {tex_escape(unit_title_en or unit_title)}}}\\[1.2cm]",
                rf"  {{\large {get_text(lang, 'title_instructor')} {tex_escape(instructor)}}}\\[0.5cm]",
                rf"  {{\large\textcolor{{darkgray}}{{{get_text(lang, 'generated_by')}}}}}\\[0.3cm]",
                r"  {\small\textcolor{darkgray}{\today}}",
                r"  \vfill",
                rf"  {{\small {get_text(lang, 'title_note')}}}",
            ]
        )
    else:
        lines.extend(
            [
                rf"  {{\Huge\bfseries\color{{accent}} {tex_escape(course_title)}}}\\[0.3cm]",
                rf"  {{\small\textcolor{{darkgray}}{{{tex_escape(course_title_en or course_title)}}}}}\\[0.8cm]",
                rf"  {{\LARGE {tex_escape(unit_title)}}}\\[0.3cm]",
                rf"  {{\small\textcolor{{darkgray}}{{{tex_escape(unit_title_en or unit_title)}}}}}\\[1.2cm]",
                rf"  {{\large {get_text(lang, 'title_instructor')} {tex_escape(instructor)}}}\\[0.5cm]",
                rf"  {{\large\textcolor{{darkgray}}{{{get_text(lang, 'generated_by')}}}}}\\[0.3cm]",
                r"  {\small\textcolor{darkgray}{\today}}",
                r"  \vfill",
                rf"  {{\small {get_text(lang, 'title_note')}}}",
            ]
        )
    lines.extend([r"\end{center}", r"\newpage"])
    return "\n".join(lines) + "\n"


def build_toc(lang: str) -> str:
    return "\n".join([r"\tableofcontents", r"\newpage"]) + "\n"


def add_toc_entry(level: str, title: str) -> str:
    """Add a manual TOC entry for starred sectioning commands."""
    return rf"\addcontentsline{{toc}}{{{level}}}{{{tex_escape(title)}}}"


# ── Content extraction ────────────────────────────────────────────────────────

def extract_vtt_text(vtt_path: Path) -> str:
    """Extract clean text from a VTT file."""
    text = vtt_path.read_text(encoding="utf-8", errors="replace")
    text = re.sub(r"WEBVTT.*?\n\n", "", text, flags=re.DOTALL)
    text = re.sub(r"\d{1,2}:\d{2}:\d{2}\.\d{3}\s*-->\s*\d{1,2}:\d{2}:\d{2}\.\d{3}", "", text)
    text = re.sub(r"<[^>]+>", "", text)
    lines = [l.strip() for l in text.splitlines() if l.strip()]
    return " ".join(lines)


def extract_pdf_text(pdf_path: Path, max_pages: int = 5) -> str:
    """Extract text from a PDF file."""
    try:
        import pdfplumber
        texts = []
        with pdfplumber.open(pdf_path) as pdf:
            for page in pdf.pages[:max_pages]:
                t = page.extract_text()
                if t:
                    texts.append(t)
        return "\n\n".join(texts)
    except Exception as e:
        return f"[PDF extraction failed: {e}]"


def resolve_existing_path(data_dir: Path, candidate: str | None) -> Path | None:
    """Resolve a manifest path against the data directory."""
    if not candidate:
        return None
    raw = Path(candidate)
    if raw.is_absolute() and raw.exists():
        return raw
    direct = data_dir / candidate
    if direct.exists():
        return direct
    name = raw.name
    if name:
        matches = sorted(data_dir.rglob(name))
        if matches:
            return matches[0]
    return None


def resolve_subtitle_path(data_dir: Path, item: dict) -> Path | None:
    """Find the local subtitle file for one manifest row."""
    candidates = [
        item.get("file"),
        item.get("subtitle_file"),
        item.get("subtitle_path"),
        item.get("vtt"),
        item.get("en_vtt"),
        item.get("zh_vtt"),
    ]
    video_stem = Path(item.get("video", "")).stem if item.get("video") else ""
    if video_stem:
        candidates.extend(
            [
                f"{video_stem}.vtt",
                f"{video_stem}.en.vtt",
                f"{video_stem}.zh-CN.vtt",
                f"{video_stem}.txt",
                f"{video_stem}.srt",
            ]
        )
    for candidate in candidates:
        path = resolve_existing_path(data_dir, candidate)
        if path and path.suffix.lower() in {".vtt", ".txt", ".srt"}:
            return path
    return None


def parse_vtt_cues(vtt_path: Path) -> list[str]:
    """Extract cue texts from a VTT file."""
    content = vtt_path.read_text(encoding="utf-8", errors="replace")
    cue_re = re.compile(
        r"^\s*(?:\d+\s*)?(?P<start>\d{1,2}:\d{2}(?::\d{2})?\.\d{3})\s*-->\s*(?P<end>\d{1,2}:\d{2}(?::\d{2})?\.\d{3})"
    )
    cues = []
    lines = content.splitlines()
    i = 0
    while i < len(lines):
        match = cue_re.match(lines[i])
        if match:
            i += 1
            text_lines = []
            while i < len(lines) and lines[i].strip():
                clean = re.sub(r"<[^>]+>", "", lines[i]).strip()
                if clean:
                    text_lines.append(clean)
                i += 1
            text = " ".join(text_lines).strip()
            if text:
                cues.append(text)
        else:
            i += 1
    return cues


def split_text_units(text: str, lang: str) -> list[str]:
    """Split extracted text into digestible units."""
    normalized = re.sub(r"\s+", " ", text).strip()
    if not normalized:
        return []
    if lang == "zh":
        parts = re.split(r"(?<=[。！？；])\s*|(?<=\n)\s*", normalized)
    else:
        parts = re.split(r"(?<=[.!?;])\s+", normalized)
    units = [p.strip() for p in parts if p and p.strip()]
    if len(units) <= 1:
        units = [p.strip() for p in re.split(r"\s{2,}|\n+", text) if p and p.strip()]
    return units


def visible_text_len(text: str) -> int:
    """Estimate how much readable text remains after LaTeX markup is stripped."""
    stripped = re.sub(r"\\[a-zA-Z@]+(?:\[[^\]]*\])?(?:\{[^{}]*\})*", " ", text)
    stripped = re.sub(r"[{}]", " ", stripped)
    stripped = re.sub(r"\s+", " ", stripped)
    return len(stripped.strip())


LANG_SNIPPET_KEYWORDS = {
    "zh": [
        "定义", "核心", "关键", "重要", "例如", "比如", "因此", "注意",
        "区别", "关系", "总结", "证明", "方法", "步骤", "结论", "本质",
        "示例", "推导", "概念",
    ],
    "en": [
        "define", "definition", "key", "important", "example", "therefore",
        "however", "difference", "relationship", "summary", "prove", "proof",
        "method", "step", "conclusion", "core", "concept", "note", "for instance",
    ],
}


SUMMARY_THEMES = {
    "zh": [
        {
            "key": "course_framing",
            "label": "课程定位",
            "summary": "这一讲主要在搭建课程框架：它强调思维转型、课程安排和学习期待，而不是新的计算技巧。",
            "keywords": [
                "课程",
                "目标",
                "欢迎",
                "开篇",
                "思维",
                "高中",
                "大学",
                "very different perspective",
                "mental ability",
                "school math",
                "university",
            ],
        },
        {
            "key": "math_as_patterns",
            "label": "核心概念",
            "summary": "这一讲把数学定义为对模式的研究，并解释为什么精确符号是进入数学语言的必要工具。",
            "keywords": [
                "数学是",
                "模式",
                "pattern",
                "符号",
                "notation",
                "定理",
                "theorem",
                "历史",
                "precise language",
            ],
        },
        {
            "key": "logic_connectives",
            "label": "形式定义",
            "summary": "这一讲梳理 AND / OR / NOT / IF...THEN 等连接词的真值条件，并提醒不要把日常语言的直觉直接搬进数学里。",
            "keywords": [
                "逻辑连接词",
                "命题",
                "and",
                "or",
                "not",
                "if",
                "then",
                "iff",
                "真值",
                "biconditional",
            ],
        },
        {
            "key": "proof_and_contradiction",
            "label": "证明路线",
            "summary": "这一讲用反证法说明素数为何不可能有限，并把构造步骤写成可检查的逻辑链。",
            "keywords": [
                "素数",
                "prime",
                "反证",
                "contradiction",
                "无穷",
                "Euclid",
            ],
        },
        {
            "key": "constraint_simplification",
            "label": "方法提醒",
            "summary": "这一讲通过区间和数轴说明如何删去冗余条件，把复杂表达压成更简洁的形式。",
            "keywords": [
                "冗余",
                "redundant",
                "区间",
                "interval",
                "数轴",
                "simplify",
                "化简",
                "superfluous",
            ],
        },
        {
            "key": "set_theory_basics",
            "label": "补充基础",
            "summary": "这一部分补齐集合论的基本语言，包括空集、子集以及并集、交集等操作。",
            "keywords": [
                "集合",
                "空集",
                "子集",
                "并集",
                "交集",
                "set",
                "empty set",
                "subset",
                "union",
                "intersection",
            ],
        },
        {
            "key": "assignment_guidance",
            "label": "作业提示",
            "summary": "这一讲主要在把概念落回题目：它说明如何把新定义用到作业和证明题里。",
            "keywords": [
                "作业",
                "assignment",
                "题",
                "problem",
                "练习",
                "homework",
            ],
        },
        {
            "key": "definition",
            "label": "定义",
            "summary": "这一讲补出一个后面会反复使用的定义，并说明它为什么重要。",
            "keywords": [
                "定义",
                "define",
                "definition",
            ],
        },
        {
            "key": "example",
            "label": "例子",
            "summary": "这一讲用具体例子把抽象概念落地，方便检查理解是否到位。",
            "keywords": [
                "例如",
                "比如",
                "举个例子",
                "example",
                "for instance",
            ],
        },
        {
            "key": "summary",
            "label": "小结",
            "summary": "这一讲把前面的材料重新收束成一个更短的结论，便于回看。",
            "keywords": [
                "总结",
                "小结",
                "summary",
                "wrap up",
                "recap",
            ],
        },
    ],
    "en": [
        {
            "key": "course_framing",
            "label": "Course framing",
            "summary": "This lecture sets up the course as a shift in mindset rather than a new bag of procedures.",
            "keywords": [
                "course",
                "goal",
                "welcome",
                "mental ability",
                "very different perspective",
                "school math",
                "university",
                "transition",
            ],
        },
        {
            "key": "math_as_patterns",
            "label": "Core concept",
            "summary": "This lecture defines mathematics as the study of patterns and explains why precise notation matters.",
            "keywords": [
                "what is mathematics",
                "patterns",
                "notation",
                "theorem",
                "precise language",
                "math is",
                "pattern",
            ],
        },
        {
            "key": "logic_connectives",
            "label": "Formal definitions",
            "summary": "This lecture lays out the truth conditions for AND, OR, NOT, IF...THEN, and IFF.",
            "keywords": [
                "logical connectives",
                "and",
                "or",
                "not",
                "if",
                "then",
                "iff",
                "truth",
                "biconditional",
            ],
        },
        {
            "key": "proof_and_contradiction",
            "label": "Proof arc",
            "summary": "This lecture uses contradiction to show why the primes cannot be finite.",
            "keywords": [
                "euclid",
                "prime",
                "primes",
                "contradiction",
                "infinite",
                "proof",
            ],
        },
        {
            "key": "constraint_simplification",
            "label": "Method",
            "summary": "This lecture shows how to remove redundant conditions and simplify interval expressions.",
            "keywords": [
                "redundant",
                "interval",
                "number line",
                "simplify",
                "superfluous",
                "constraint",
            ],
        },
        {
            "key": "set_theory_basics",
            "label": "Background reading",
            "summary": "This reading fills in the basic set-theory language: empty set, subset, union, and intersection.",
            "keywords": [
                "set",
                "empty set",
                "subset",
                "union",
                "intersection",
            ],
        },
        {
            "key": "assignment_guidance",
            "label": "Assignment guidance",
            "summary": "This lecture turns the abstract ideas back into problem solving and homework strategy.",
            "keywords": [
                "assignment",
                "problem",
                "homework",
                "exercise",
                "question",
            ],
        },
        {
            "key": "definition",
            "label": "Definition",
            "summary": "This lecture introduces a definition that the rest of the unit depends on.",
            "keywords": [
                "define",
                "definition",
            ],
        },
        {
            "key": "example",
            "label": "Example",
            "summary": "This lecture grounds the idea with a concrete example.",
            "keywords": [
                "example",
                "for instance",
                "say",
            ],
        },
        {
            "key": "summary",
            "label": "Summary",
            "summary": "This lecture closes by pulling the main points back together.",
            "keywords": [
                "summary",
                "recap",
                "wrap up",
            ],
        },
    ],
}


def classify_summary_theme(snippet: str, lang: str) -> str | None:
    """Map a snippet to a high-level theme so auto-digests stay abstract."""
    lowered = snippet.lower()
    for theme in SUMMARY_THEMES.get(lang, []):
        for keyword in theme.get("keywords", []):
            key = keyword.lower()
            if key in lowered or keyword in snippet:
                return str(theme["key"])
    return None


def theme_summary(theme_key: str, lang: str) -> tuple[str, str] | None:
    for theme in SUMMARY_THEMES.get(lang, []):
        if theme["key"] == theme_key:
            return str(theme["label"]), str(theme["summary"])
    return None


def score_snippet(snippet: str, lang: str, index: int, total: int) -> int:
    """Heuristically score a text snippet for salience."""
    lower = snippet.lower()
    score = 0
    for word in LANG_SNIPPET_KEYWORDS.get(lang, []):
        if word in lower:
            score += 3 if len(word) > 3 else 2
    if len(snippet) >= 120:
        score += 2
    elif len(snippet) >= 60:
        score += 1
    if index == 0:
        score += 1
    if index == total - 1:
        score += 1
    return score


def pick_snippets(snippets: list[str], lang: str, limit: int = 4) -> list[str]:
    """Select the most informative snippets while keeping source order."""
    normalized = [re.sub(r"\s+", " ", s).strip() for s in snippets if s and s.strip()]
    normalized = [s for s in normalized if len(s) >= 20]
    if not normalized:
        return []
    scored = [
        (score_snippet(snippet, lang, index, len(normalized)), index, snippet)
        for index, snippet in enumerate(normalized)
    ]
    scored.sort(key=lambda item: (-item[0], item[1]))
    if scored and scored[0][0] == 0:
        selected = scored[: min(limit, len(scored))]
    else:
        selected = scored[: min(limit, len(scored))]
    selected.sort(key=lambda item: item[1])
    return [snippet for _, _, snippet in selected]


def compact_snippet(snippet: str, lang: str, max_len: int = 160) -> str:
    """Trim filler and keep a transcript snippet readable as a bullet."""
    text = re.sub(r"\s+", " ", snippet).strip()
    if not text:
        return ""
    if lang == "zh":
        for prefix in [
            "这一讲",
            "这一部分",
            "我们",
            "接下来",
            "然后",
            "最后",
            "现在",
        ]:
            if text.startswith(prefix):
                text = text[len(prefix):].lstrip("，,。:：-— ")
                break
    else:
        lower = text.lower()
        for prefix in [
            "this lecture ",
            "in this lecture ",
            "in this module, ",
            "we are going to ",
            "we're going to ",
            "now ",
            "next, ",
            "finally, ",
        ]:
            if lower.startswith(prefix):
                text = text[len(prefix):].lstrip(",.:- ")
                break
    if len(text) > max_len:
        cut_points = [text.rfind(p, 0, max_len) for p in ["。", "！", "？", "；", ".", "!", "?", ";", "，", ","]]
        cut = max(cut_points)
        if cut < max_len // 2:
            cut = max_len
        text = text[:cut].rstrip()
        if not text.endswith("…"):
            text += "…"
    return text


def build_auto_digest(snippets: list[str], lang: str, label: str, intro: str, limit: int = 5) -> str:
    """Render a lecture-local auto digest block from transcript snippets."""
    selected = pick_snippets(snippets, lang, limit=limit)
    if not selected:
        return ""
    parts = [r"\begin{keyconcept}"]
    parts.append(rf"\textbf{{{tex_escape(label)}}}")
    parts.append(tex_escape(intro))
    parts.append(r"\begin{itemize}")
    for snippet in selected[:limit]:
        compact = compact_snippet(snippet, lang)
        if compact:
            parts.append(f"  \\item {tex_escape(compact)}")
    parts.append(r"\end{itemize}")
    parts.append(r"\end{keyconcept}")
    return "\n".join(parts)


def build_transcript_digest(subtitle_path: Path | None, lang: str, lecture_title: str = "") -> str:
    """Create a digest from subtitle content when hand-authored content is sparse."""
    if not subtitle_path or not subtitle_path.exists():
        return ""
    raw_text = subtitle_path.read_text(encoding="utf-8", errors="replace")
    if lang == "en" and contains_cjk(raw_text):
        raise SystemExit(f"English output requires English subtitle text: {subtitle_path.name}")
    if subtitle_path.suffix.lower() == ".vtt":
        snippets = parse_vtt_cues(subtitle_path)
    else:
        snippets = split_text_units(raw_text, lang)
    if lecture_title:
        label = f"{lecture_title} 的字幕要点" if lang == "zh" else f"{lecture_title} transcript notes"
    else:
        label = "字幕要点" if lang == "zh" else "Transcript notes"
    intro = (
        "根据字幕自动提炼，这一讲再补充几条最值得记住的线索。"
        if lang == "zh"
        else "Expanded automatically from the transcript to keep the lecture's main lines visible."
    )
    return build_auto_digest(snippets, lang, label, intro)


def build_pdf_digest(pdf_path: Path | None, lang: str, resource_name: str = "") -> str:
    """Create a digest from supplementary PDF text when no hand-authored summary exists."""
    if not pdf_path or not pdf_path.exists():
        return ""
    if lang == "en" and resource_name and not display_resource_name(resource_name, pdf_path, lang):
        return ""
    extracted = extract_pdf_text(pdf_path, max_pages=4)
    if not extracted or extracted.startswith("[PDF extraction failed"):
        return ""
    if lang == "en" and not is_likely_english_text(extracted):
        return ""
    snippets = split_text_units(extracted, lang)
    label = "补充材料要点" if lang == "zh" else "Reading notes"
    intro = (
        "根据补充材料自动提炼，这份阅读再补几条关键线索。"
        if lang == "zh"
        else "Expanded automatically from the extracted PDF text to surface the main points."
    )
    return build_auto_digest(snippets, lang, label, intro, limit=3)


def render_text_box(title: str, lines: list[str]) -> str:
    """Render a compact framed box with monospaced multi-line content."""
    cleaned = [line.rstrip() for line in lines if line and line.strip()]
    if not cleaned:
        return ""
    body = r"\\ ".join(tex_escape(line) for line in cleaned)
    return "\n".join(
        [
            r"\begin{center}",
            r"\fcolorbox{darkgray}{white}{%",
            r"\begin{minipage}{0.94\linewidth}",
            rf"\textbf{{{tex_escape(title)}}}\\[0.35em]",
            r"\ttfamily\small",
            body,
            r"\end{minipage}}",
            r"\end{center}",
        ]
    )


def normalize_plain_items(value) -> list[str]:
    """Flatten a value into a clean list of plain-text items."""
    if value is None:
        return []
    if isinstance(value, str):
        text = re.sub(r"\s+", " ", value).strip()
        return [text] if text else []
    if isinstance(value, dict):
        items: list[str] = []
        for key in ("summary", "lead", "body", "text", "key_points", "bullets", "diagram", "visual_notes", "discussion"):
            if key in value:
                items.extend(normalize_plain_items(value[key]))
        return items
    if isinstance(value, (list, tuple)):
        items: list[str] = []
        for item in value:
            items.extend(normalize_plain_items(item))
        return items
    text = re.sub(r"\s+", " ", str(value)).strip()
    return [text] if text else []


def normalize_line_items(value) -> list[str]:
    """Flatten a value into lines, preserving explicit line breaks when present."""
    if isinstance(value, str):
        lines = [line.strip() for line in value.splitlines() if line.strip()]
        if lines:
            return lines
    return normalize_plain_items(value)


def collect_visible_text(value) -> str:
    """Collect all text fragments from a structured block for length checks."""
    return " ".join(normalize_plain_items(value))


def render_itemize_box(title: str, items: list[str]) -> str:
    """Render a framed bullet list box."""
    cleaned = [item.strip() for item in items if item and item.strip()]
    if not cleaned:
        return ""
    parts = [r"\begin{keyconcept}", rf"\textbf{{{tex_escape(title)}}}", r"\begin{itemize}"]
    for item in cleaned:
        parts.append(f"  \\item {tex_escape(item)}")
    parts.append(r"\end{itemize}")
    parts.append(r"\end{keyconcept}")
    return "\n".join(parts)


def render_content_block(block, lang: str) -> str:
    """Render a lecture or unit content block in either legacy or structured form."""
    if not block:
        return ""
    if isinstance(block, str):
        return block
    if isinstance(block, list):
        paragraphs = [part for part in normalize_plain_items(block)]
        return "\n\n".join(paragraphs)
    if not isinstance(block, dict):
        return tex_escape(str(block))

    parts: list[str] = []
    summary = block.get("summary") or block.get("body") or block.get("text")
    if summary:
        if isinstance(summary, str):
            parts.append(summary)
        else:
            summary_parts = [part for part in normalize_plain_items(summary)]
            if summary_parts:
                parts.append("\n\n".join(summary_parts))

    key_points = block.get("key_points") or block.get("bullets")
    if key_points:
        parts.append(render_itemize_box(block.get("key_points_title", ""), normalize_plain_items(key_points)))

    diagram = block.get("diagram")
    if diagram:
        title = block.get("diagram_title") or get_text(lang, "diagram")
        parts.append(render_text_box(title, normalize_line_items(diagram)))

    visual_notes = block.get("visual_notes") or block.get("frame_notes")
    if visual_notes:
        title = block.get("visual_notes_title") or get_text(lang, "visual_notes")
        parts.append(render_itemize_box(title, normalize_line_items(visual_notes)))

    discussion = block.get("discussion")
    if discussion:
        title = block.get("discussion_title") or get_text(lang, "discussion")
        parts.append(render_itemize_box(title, normalize_line_items(discussion)))

    extra = block.get("extra")
    if extra:
        parts.append(render_content_block(extra, lang))

    return "\n\n".join(part for part in parts if part)


def block_visible_len(block) -> int:
    """Estimate visible text length for strings or structured content blocks."""
    return visible_text_len(collect_visible_text(block))


def tex_escape(text: str) -> str:
    """Escape special LaTeX characters."""
    return (
        text.replace("\\", r"\textbackslash{}")
        .replace("&", r"\&")
        .replace("%", r"\%")
        .replace("$", r"\$")
        .replace("#", r"\#")
        .replace("_", r"\_")
        .replace("{", r"\{")
        .replace("}", r"\}")
        .replace("~", r"\textasciitilde{}")
        .replace("^", r"\textasciicircum{}")
    )


# ── Handout generation ────────────────────────────────────────────────────────

def generate_handout(
    data_dir: Path,
    course_title: str,
    unit_title: str,
    instructor: str,
    output: Path,
    course_title_en: str = "",
    unit_title_en: str = "",
    lang: str = "zh",
    insert_keyframes: bool = False,
):
    """Generate a complete LaTeX handout."""

    if lang not in TEXT:
        raise SystemExit(f"unsupported language: {lang}")

    display_course_title = course_title if lang == "zh" else (course_title_en or course_title)
    display_unit_title = unit_title if lang == "zh" else (unit_title_en or unit_title)
    if lang == "en" and (contains_cjk(display_course_title) or contains_cjk(display_unit_title)):
        raise SystemExit(
            "English output requires English course and unit titles; pass --course-title-en and --unit-title-en"
        )

    # Load manifest
    manifest_path = data_dir / "manifest.json"
    if not manifest_path.exists():
        print(f"Error: {manifest_path} not found", file=sys.stderr)
        sys.exit(1)

    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))

    # Load keyframes
    keyframes_path = data_dir / "keyframes.json"
    keyframes = []
    if keyframes_path.exists():
        keyframes = json.loads(keyframes_path.read_text(encoding="utf-8"))

    # Build LaTeX
    tex = []

    tex.append(build_preamble(lang, display_course_title, display_unit_title, instructor, data_dir))
    tex.append(build_title_page(lang, course_title, unit_title, instructor, course_title_en, unit_title_en))
    tex.append(build_toc(lang))

    # ── Load content.json (language-aware) ──
    content_json_path = data_dir / ("content_en.json" if lang == "en" else "content.json")
    if content_json_path.exists():
        content_data = json.loads(content_json_path.read_text(encoding="utf-8"))
    else:
        content_data = {}
    lecture_titles = content_data.get("lecture_titles", {})

    # ── Knowledge Map ──
    knowledge_map = content_data.get("knowledge_map", [])
    if knowledge_map:
        tex.append(rf"\section*{{{get_text(lang, 'knowledge_map')}}}")
        tex.append(add_toc_entry("section", get_text(lang, "knowledge_map")))
        tex.append(r"\begin{longtable}{p{3.1cm}p{10.2cm}}")
        tex.append(r"\toprule")
        tex.append(rf"{get_text(lang, 'knowledge_topic')} & {get_text(lang, 'knowledge_question')} \\")
        tex.append(r"\midrule")
        for row in knowledge_map:
            topic = row.get("topic", "")
            question = row.get("question", "")
            tex.append(f"{topic} & {question} \\\\")
        tex.append(r"\bottomrule")
        tex.append(r"\end{longtable}")
        tex.append("")

    # ── Section 0: Overview ──
    overview = content_data.get("overview", "")
    tex.append(rf"\section*{{{get_text(lang, 'overview')}}}")
    tex.append(add_toc_entry("section", get_text(lang, "overview")))
    if overview:
        tex.append(render_content_block(overview, lang))
    else:
        tex.append(
            r"This unit covers the core concepts of the course."
            if lang == "en"
            else r"本单元涵盖课程的核心概念。"
        )
    tex.append("")

    # ── Per-lecture sections ──
    lecture_summaries = content_data.get("lectures", {})
    for i, item in enumerate(manifest):
        subtitle_path = resolve_subtitle_path(data_dir, item)
        video_stem_key = item.get("video", "").replace(".mp4", "") if item.get("video") else ""
        vtt_source_name = subtitle_path.stem if subtitle_path else item.get("en_vtt", item.get("vtt", "")).replace(".vtt", "")
        vtt_stem_key = re.sub(r"\.(en|zh-CN|zh-TW|ja|ko|fr|de|es|pt|ar)$", "", vtt_source_name)
        lecture_title = item["title"]
        if lang == "en":
            lecture_title = (
                lecture_titles.get(video_stem_key)
                or lecture_titles.get(vtt_stem_key)
                or item.get("title_en")
                or item.get("title")
            )
            if contains_cjk(lecture_title):
                raise SystemExit(
                    "English output requires English lecture titles in manifest.json or content_en.json"
                )
        section_num = i + 1

        tex.append(f"\\section*{{{section_num}. {tex_escape(lecture_title)}}}")
        tex.append(add_toc_entry("section", f"{section_num}. {lecture_title}"))

        # Video link with duration
        video_url = item.get("page_url", "")
        duration = item.get("duration", "")
        dur_str = f"({duration})" if lang == "en" and duration else f"（{duration}）" if duration else ""
        if video_url:
            tex.append(
                rf"\noindent\textbf{{{get_text(lang, 'lesson_review')}}}\videolink{{{video_url}}}{{{tex_escape(lecture_title)}}}{dur_str}"
            )
        tex.append("")

        # Per-lecture content from content.json
        lecture_content = lecture_summaries.get(video_stem_key) or lecture_summaries.get(vtt_stem_key) or ""
        auto_lecture_content = build_transcript_digest(subtitle_path, lang, lecture_title)
        if lecture_content:
            tex.append(render_content_block(lecture_content, lang))
            if block_visible_len(lecture_content) < 420 and auto_lecture_content:
                tex.append("")
                tex.append(auto_lecture_content)
        elif auto_lecture_content:
            tex.append(auto_lecture_content)
        else:
            if lang == "en":
                tex.append("This lecture summary should be added to content_en.json.")
            else:
                tex.append("这一讲的总结尚未补齐，可先从字幕中提炼主线。")
            tex.append("")
        tex.append("")

        # Supplementary materials
        if item.get("resources"):
            supplements_path = data_dir / ("supplements_en.json" if lang == "en" else "supplements.json")
            supplements_data = {}
            if supplements_path.exists():
                supplements_data = json.loads(supplements_path.read_text(encoding="utf-8"))
            for res_name in item["resources"]:
                res_path = resolve_existing_path(data_dir, res_name)
                if res_name in supplements_data:
                    info = supplements_data[res_name]
                    tex.append(f"\\textbf{{📎 {info['title']}}}")
                    escaped_name = tex_escape(res_name)
                    tex.append(f"\\hfill{{\\small\\texttt{{{escaped_name}}}}}")
                    tex.append("")
                    tex.append(rf"\begin{{supplement}}{{{get_text(lang, 'supplement_summary')}}}")
                    tex.append(r"\begin{itemize}")
                    for para in info.get("summary", []):
                        tex.append(f"  \\item {para}")
                    tex.append(r"\end{itemize}")
                    if visible_text_len("\n".join(info.get("summary", []))) < 260:
                        auto_supplement = build_pdf_digest(res_path, lang, res_name)
                        if auto_supplement:
                            tex.append("")
                            tex.append(auto_supplement)
                    tex.append(r"\end{supplement}")
                    tex.append("")
                else:
                    sep = ":" if lang == "en" else "："
                    display_name = display_resource_name(res_name, res_path, lang)
                    line = f"\\textbf{{{get_text(lang, 'supplement_label')}}}{sep}"
                    if display_name:
                        line += f"\\texttt{{{tex_escape(display_name)}}}"
                    tex.append(line)
                    auto_supplement = build_pdf_digest(res_path, lang, res_name)
                    if auto_supplement:
                        tex.append(auto_supplement)
                    tex.append("")

        # Keyframes (optional)
        if insert_keyframes:
            video_stem = item.get("video", "").replace(".mp4", "") if item.get("video") else ""
            lecture_frames = [kf for kf in keyframes if (video_stem and video_stem in kf.get("video", "")) or (vtt_stem_key and vtt_stem_key in kf.get("vtt", ""))]
            if lecture_frames:
                for kf in lecture_frames[:2]:
                    time_label = f"{int(kf['time']):04d}s" if kf['time'] < 60 else f"{int(kf['time'])//60:02d}m{int(kf['time'])%60:02d}s"
                    frame_file = f"{vtt_stem_key}_{time_label}_{kf['reason']}.png"
                    frame_path = data_dir / "frames" / frame_file
                    if frame_path.exists():
                        reason_label = get_text(lang, "keyframe_reason").get(kf["reason"], kf["reason"])
                        caption = get_text(lang, "keyframe_caption").format(time=int(kf["time"]), reason=reason_label)
                        tex.append(f"\\keyframe{{{frame_file}}}{{{caption}}}")
        tex.append("")

    # ── Unit synthesis / discussion ──
    next_section_num = len(manifest) + 1
    synthesis = content_data.get("synthesis", "")
    if synthesis:
        section_title = f"{next_section_num}. {get_text(lang, 'synthesis')}"
        tex.append(rf"\section*{{{section_title}}}")
        tex.append(add_toc_entry("section", section_title))
        tex.append(render_content_block(synthesis, lang))
        tex.append("")
        next_section_num += 1

    discussion = content_data.get("discussion", "")
    if discussion:
        section_title = f"{next_section_num}. {get_text(lang, 'discussion')}"
        tex.append(rf"\section*{{{section_title}}}")
        tex.append(add_toc_entry("section", section_title))
        tex.append(render_content_block(discussion, lang))
        tex.append("")
        next_section_num += 1

    # ── Key Takeaways ──
    key_takeaways = content_data.get("key_takeaways", [])
    if key_takeaways:
        takeaway_num = next_section_num
        if lang == "en":
            section_title = f"{takeaway_num}. {get_text(lang, 'key_takeaways')}"
            tex.append(rf"\section*{{{section_title}}}")
            tex.append(add_toc_entry("section", section_title))
        else:
            n = len(key_takeaways)
            cn_num = {3: "三", 4: "四", 5: "五", 6: "六", 7: "七", 8: "八", 9: "九", 10: "十"}.get(n, str(n))
            section_title = f"{takeaway_num}. {get_text(lang, 'key_takeaways').format(count=cn_num)}"
            tex.append(rf"\section*{{{section_title}}}")
            tex.append(add_toc_entry("section", section_title))
        tex.append(r"\begin{enumerate}")
        for t in key_takeaways:
            tex.append(f"  \\item {t}")
        tex.append(r"\end{enumerate}")
        tex.append("")
        next_section_num += 1

    # ── Exercises ──
    exercises = content_data.get("exercises", {})
    answers = content_data.get("answers", {})
    if exercises:
        ex_num = next_section_num
        section_title = f"{ex_num}. {get_text(lang, 'exercises')}"
        tex.append(rf"\section*{{{section_title}}}")
        tex.append(add_toc_entry("section", section_title))

        # A. Multiple choice
        choice = exercises.get("choice", [])
        if choice:
            tex.append(rf"\subsection*{{A. {get_text(lang, 'mcq').format(count=len(choice))}}}")
            tex.append(r"\begin{enumerate}")
            for q in choice:
                tex.append(f"  \\item {q['q']}\\\\")
                options = " \\quad ".join(q.get("options", []))
                tex.append(f"  {options}")
                tex.append("")
            tex.append(r"\end{enumerate}")
            tex.append("")

        # B. True/False
        truefalse = exercises.get("truefalse", [])
        if truefalse:
            tex.append(rf"\subsection*{{B. {get_text(lang, 'truefalse').format(count=len(truefalse))}}}")
            tex.append(r"\begin{enumerate}")
            for q in truefalse:
                tex.append(f"  \\item {q}(\\quad)" if lang == "en" else f"  \\item {q}（\\quad）")
            tex.append(r"\end{enumerate}")
            tex.append("")

        # C. Short answer
        shortanswer = exercises.get("shortanswer", [])
        if shortanswer:
            tex.append(rf"\subsection*{{C. {get_text(lang, 'shortanswer').format(count=len(shortanswer))}}}")
            tex.append(r"\begin{enumerate}")
            for q in shortanswer:
                tex.append(f"  \\item {q}")
            tex.append(r"\end{enumerate}")
            tex.append("")
        next_section_num += 1

    # ── Answers ──
    if answers:
        ans_num = next_section_num
        section_title = f"{ans_num}. {get_text(lang, 'answers')}"
        tex.append(rf"\section*{{{section_title}}}")
        tex.append(add_toc_entry("section", section_title))

        if answers.get("choice"):
            tex.append(rf"\subsection*{{{get_text(lang, 'mcq_answers')}}}")
            tex.append(answers["choice"])
            tex.append("")

        if answers.get("truefalse"):
            tex.append(rf"\subsection*{{{get_text(lang, 'truefalse_answers')}}}")
            tex.append(answers["truefalse"])
            tex.append("")

        if answers.get("shortanswer"):
            tex.append(rf"\subsection*{{{get_text(lang, 'shortanswer_answers')}}}")
            tex.append(r"\begin{enumerate}")
            for a in answers["shortanswer"]:
                tex.append(f"  \\item {a}")
            tex.append(r"\end{enumerate}")
            tex.append("")

    # End document
    tex.append(r"\end{document}")
    
    # Write output
    output.write_text("\n".join(tex), encoding="utf-8")
    print(f"Generated: {output}")
    print(f"  Lectures: {len(manifest)}")
    print(f"  Keyframes: {len(keyframes)}")
    print(f"  Compile with: xelatex {output.name} && xelatex {output.name}")


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Generate a polished LaTeX handout.")
    parser.add_argument("--data-dir", required=True, help="Directory with VTT/PDF/frames")
    parser.add_argument("--course-title", required=True, help="Course title in the output language")
    parser.add_argument("--unit-title", required=True, help="Unit title in the output language")
    parser.add_argument("--course-title-en", default="", help="English course title used for en mode and as a subtitle in zh mode")
    parser.add_argument("--unit-title-en", default="", help="English unit title used for en mode and as a subtitle in zh mode")
    parser.add_argument("--instructor", default="")
    parser.add_argument("--lang", default="zh", choices=["zh", "en"], help="Output language (en requires content_en.json and English titles)")
    parser.add_argument("--keyframes", action="store_true", default=False, help="Insert keyframe screenshots (default: off)")
    parser.add_argument("--output", required=True, help="Output .tex file")
    args = parser.parse_args()
    
    generate_handout(
        data_dir=Path(args.data_dir),
        course_title=args.course_title,
        unit_title=args.unit_title,
        instructor=args.instructor,
        output=Path(args.output),
        course_title_en=args.course_title_en,
        unit_title_en=args.unit_title_en,
        lang=args.lang,
        insert_keyframes=args.keyframes,
    )


if __name__ == "__main__":
    main()
